version: '3.8'

services:
  postgres_db:
    image: postgres
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - teddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data

  api-teddy:
    container_name: teddy-api
    image: morico2302/teddy-api:latest
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - teddy-network

networks:
  teddy-network:
    name: teddy-network

volumes:
  db:
